### ISSUE TITLE
Deleting orders

### ISSUE THREAD

**Issue by newswim** [nozzlegear/Gearworks#7]
Is this app capable of actually removing orders which were placed while the store _wasn't_ in test mode?

**Comment by nozzlegear** [comment]
This app should definitely be able to remove orders, it's using [Shopify Prime](https://github.com/nozzlegear/shopify-prime) to handle the API calls.

(Sidenote: I've got a huge update coming for this project in the next few weeks. Almost every file is going to have some or many changes.)

**Comment by newswim** [comment]
Cool! This is a really impressive work. I've tried making raw API calls and get..

```
{
  "errors": {
    "base": [
      "Cannot delete orders brokered by Shopify"
    ]
  }
}
```

Also from https://help.shopify.com/api/reference/order#destroy

> Delete an order. Orders that interact with an online gateway cannot be deleted.

We're using Shopify Payments, if there is a way around this I'd really like to find out.

**Comment by nozzlegear** [comment]
Oh shoot, sorry I completely forgot about that! I believe the API only lets you delete orders that were created by the API. In your case it's probably best to close the order instead, which will archive it and remove it from the merchant's dashboard unless they search for archived orders.
